/*
 *  Copyright 2013 Cloud4SOA, www.cloud4soa.eu
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */


/**
 * generated by http://RDFReactor.semweb4j.org ($Id: CodeGenerator.java 1765 2010-02-11 09:51:13Z max.at.xam.de $) on 9/16/11 12:57 PM
 */
package eu.cloud4soa.api.datamodel.semantic.foaf;

import com.viceversatech.rdfbeans.annotations.RDF;
import com.viceversatech.rdfbeans.annotations.RDFBean;
import com.viceversatech.rdfbeans.annotations.RDFSubject;
import eu.cloud4soa.api.datamodel.semantic.Thing;
import java.net.URI;
/**
 * This class manages access to these properties:
 * <ul>
 *   <li> Creator </li>
 *   <li> Elements1_1Format </li>
 *   <li> Elements1_1Language </li>
 *   <li> Link </li>
 *   <li> Primarytopic </li>
 *   <li> Sha1sum_hex_ </li>
 *   <li> Subject </li>
 *   <li> Topic </li>
 * </ul>
 *
 * This class was generated by <a href="http://RDFReactor.semweb4j.org">RDFReactor</a> on 9/16/11 12:57 PM
 * Modified version 0.1
 */
@RDFBean("http://xmlns.com/foaf/0.1/Document")
public class Document extends Thing {

	private Thing primarytopic;
	private Thing sha1sum_hex_;
	private Thing topic;
	private java.net.URI link;




	@Override
	@RDFSubject(prefix="http://xmlns.com/foaf/0.1/Document")
	public String getUriId() {
		return super.getUriId();
	}
	


    @RDF("http://xmlns.com/foaf/0.1/primaryTopic")
	public Thing getPrimarytopic() {
		return primarytopic;
	}
	
	public void setPrimarytopic( Thing primarytopic ) {
		this.primarytopic = primarytopic;
	}
    @RDF("http://xmlns.com/foaf/0.1/sha1")
	public Thing getSha1sum_hex_() {
		return sha1sum_hex_;
	}
	
	public void setSha1sum_hex_( Thing sha1sum_hex_ ) {
		this.sha1sum_hex_ = sha1sum_hex_;
	}

    @RDF("http://xmlns.com/foaf/0.1/topic")
	public Thing getTopic() {
		return topic;
	}
	
	public void setTopic( Thing topic ) {
		this.topic = topic;
	}
        
        @RDF("http://www.cloud4soa.eu/v0.1/enterprise-domain#link")
	public URI getLink() {
		return link;
	}
	
	public void setLink( URI link ) {
		this.link = link;
	}

}