/*
 *  Copyright 2013 Cloud4SOA, www.cloud4soa.eu
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */


package eu.cloud4soa.relational.persistence;

import eu.cloud4soa.relational.datamodel.PubKey;
import eu.cloud4soa.relational.datamodel.User;

import eu.cloud4soa.relational.persistence.support.AbstractHbmDao;

import java.util.List;
import org.hibernate.SessionFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

/**
 * Created with IntelliJ IDEA.
 * User: pgouvas
 * Date: 8/2/12
 * Time: 3:17 PM
 */
@Repository
public class PubKeyRepository extends AbstractHbmDao<PubKey> implements IPubKeyRepository {
    
    @Autowired
    public PubKeyRepository(SessionFactory sessionFactory) {
            super(sessionFactory, PubKey.class);
    }
        
    /*
    * Will produce autogenerated DAO Impl
    */
    public List<PubKey> findByPubkeyid(Long pubkeyid){
        List<PubKey> pubKeyList = this.find("id = ?", pubkeyid);
        return pubKeyList;
    }

    public List<PubKey> findByUser(User user){
        List<PubKey> pubKeyList = this.find("user.id = ?", user.getId());
        return pubKeyList;
    }

    public List<PubKey> findByPubkey(String pubkey){
        List<PubKey> pubKeyList = this.find("pubkey = ?", pubkey);
        return pubKeyList;    
    }

    public List<PubKey> findByUserAndPubkey(User user, String pubkey){
        List<PubKey> pubKeyList = this.find("pubkey = ? AND user.id = ?", pubkey, user.getId());
        return pubKeyList;
    }

    public List<PubKey> findByUserAndPubkeyid(User user, Long pubkeyid){
        List<PubKey> pubKeyList = this.find("id = ? AND user.id = ?", pubkeyid, user.getId());
        return pubKeyList;
    }

}
