/*
 *  Copyright 2013 Cloud4SOA, www.cloud4soa.eu
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */


/**
 * generated by http://RDFReactor.semweb4j.org ($Id: CodeGenerator.java 1765 2010-02-11 09:51:13Z max.at.xam.de $) on 9/19/11 6:31 PM
 */
package eu.cloud4soa.api.datamodel.semantic.measure;

import com.viceversatech.rdfbeans.annotations.RDFBean;
import com.viceversatech.rdfbeans.annotations.RDFSubject;
/**
 * This class manages access to these properties:
 * <ul>
 *   <li> Http___purl_org_dc_terms_description </li>
 *   <li> Manual </li>
 *   <li> Supplier </li>
 *   <li> Www_cloud4soa_euv0_1infrastructural_domainBandwidth </li>
 *   <li> Www_cloud4soa_euv0_1infrastructural_domainName </li>
 * </ul>
 *
 * This class was generated by <a href="http://RDFReactor.semweb4j.org">RDFReactor</a> on 9/19/11 6:31 PM
 * Modified version 0.1
 */
@RDFBean("http://www.cloud4soa.eu/v0.1/measure#Capacity")
public class Capacity extends MeasurementConcept {


	@Override
	@RDFSubject(prefix="http://www.cloud4soa.eu/v0.1/measure#")
	public String getUriId() {
		return super.getUriId();
	}
	

}